# Eeveaem Items List
import random
from .CoreItemMap import ItemMap
class EeveaemItem:
    def __init__(self, Name, FrontDescription,BackDescription,Color,MinWeight,MaxWeight,MaterialType,ItemType,
                 MinDurability,MaxDurability,MinAtk,MaxAtk,Worn,Range,Magical,Tainted,Turned,SkillTree,
                 SocketList,MinSocketCount,MaxSocketCount,Level,MinFireAtk,MaxFireAtk,MinElectricAtk,
                 MaxElectricAtk,MinColdAtk,MaxColdAtk,MinToxinAtk,MaxToxinAtk,Storage,Emotes,ToxinType,
                 MinDefence,MaxDefence,MinBonusExp,MaxBonusExp,MagicAttributes,Fixed):
        self.Name = Name
        self.FrontDescription = FrontDescription
        self.BackDescription = BackDescription
        self.Storage = Storage
        self.Emotes = Emotes
        self.Turned = Turned
        self.Level = Level
        self.SkillTree = SkillTree
        self.Color = Color
        self.MinWeight = MinWeight
        self.MaxWeight = MaxWeight
        self.MaterialType = MaterialType
        self.ItemType = ItemType
        self.MinDurability = MinDurability
        self.MaxDurability = MaxDurability
        self.MinAtk = MinAtk
        self.MaxAtk = MaxAtk
        self.MinDefence = MinDefence
        self.MaxDefence = MaxDefence
        self.MinBonusExp = MinBonusExp
        self.MaxBonusExp = MaxBonusExp
        self.MinFireAtk = MinFireAtk
        self.MaxFireAtk = MaxFireAtk
        self.MinElectricAtk = MinElectricAtk
        self.MaxElectricAtk = MaxElectricAtk
        self.MinColdAtk = MinColdAtk
        self.MaxColdAtk = MaxColdAtk
        self.MinToxinAtk = MinToxinAtk
        self.MaxToxinAtk = MaxToxinAtk
        self.MinSocketCount = MinSocketCount
        self.MaxSocketCount = MaxSocketCount
        self.SocketList = SocketList
        self.Tainted = Tainted
        self.ToxinType = ToxinType
        self.Worn = Worn
        self.Range = Range
        self.Magical = Magical
        self.MagicAttributes = MagicAttributes
        self.Fixed = Fixed

class WoodenWall(EeveaemItem):
    def __init__(self):
        self.Name = 'Wooden Wall'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'].format(self.Color),
                         MaterialType = ItemMap[self.Name]['MaterialType'][random.randint(0,(len(ItemMap[self.Name]['MaterialType'])-1))],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'].format(self.Color),
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)

class Plate(EeveaemItem):
    def __init__(self):
        self.Name = 'Plate'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'],
                         MaterialType = ItemMap[self.Name]['MaterialType'][random.randint(0,(len(ItemMap[self.Name]['MaterialType'])-1))],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'],
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)

class Cup(EeveaemItem):
    def __init__(self):
        self.Name = 'Cup'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'],
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         MaterialType = ItemMap[self.Name]['MaterialType'],
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)

class Mug(EeveaemItem):
    def __init__(self):
        self.Name = 'Mug'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'],
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         MaterialType = ItemMap[self.Name]['MaterialType'],
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)
class Platter(EeveaemItem):
    def __init__(self):
        self.Name = 'Platter'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'],
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         MaterialType = ItemMap[self.Name]['MaterialType'],
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)
class WineGlass(EeveaemItem):
    def __init__(self):
        self.Name = 'WineGlass'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'],
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         MaterialType = ItemMap[self.Name]['MaterialType'],
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)

class WineGlass(EeveaemItem):
    def __init__(self,Material):
        self.Name = 'WineGlass'
        super().__init__(Name=self.Name,
                         MinWeight = ItemMap[self.Name]['MinWeight'],
                         Color = ItemMap[self.Name]['Color'][random.randint(0,len(ItemMap[self.Name]['Color'])-1)],
                         FrontDescription = ItemMap[self.Name]['FrontDescription'],
                         SkillTree = ItemMap[self.Name]['SkillTree'],
                         BackDescription = ItemMap[self.Name]['BackDescription'],
                         MaxWeight = ItemMap[self.Name]['MaxWeight'],
                         MaterialType = Material.title(),
                         ItemType = ItemMap[self.Name]['ItemType'],
                         Storage = ItemMap[self.Name]['Storage'],
                         Emotes = ItemMap[self.Name]['Emotes'],
                         Level = ItemMap[self.Name]['Level'],
                         MinAtk = ItemMap[self.Name]['MinAtk'],
                         MinDurability = ItemMap[self.Name]['MinDurability'],
                         MaxAtk = ItemMap[self.Name]['MaxAtk'],
                         MinSocketCount = ItemMap[self.Name]['MinSocketCount'],
                         MaxSocketCount = ItemMap[self.Name]['MaxSocketCount'],
                         SocketList = ItemMap[self.Name]['SocketList'],
                         MaxDurability = ItemMap[self.Name]['MaxDurability'][self.MaterialType],
                         MinDefence = ItemMap[self.Name]['MinDefence'],
                         MaxDefence = ItemMap[self.Name]['MaxDefence'],
                         Worn = ItemMap[self.Name]['Worn'],
                         Range = ItemMap[self.Name]['Range'],
                         MinBonusExp = ItemMap[self.Name]['MinBonusExp'],
                         MaxBonusExp = ItemMap[self.Name]['MaxBonusExp'],
                         MinFireAtk = ItemMap[self.Name]['MinFireAtk'],
                         MaxFireAtk = ItemMap[self.Name]['MaxFireAtk'],
                         MinElectricAtk = ItemMap[self.Name]['MinElectricAtk'],
                         MaxElectricAtk = ItemMap[self.Name]['MaxElectricAtk'],
                         MinColdAtk = ItemMap[self.Name]['MinColdAtk'],
                         MaxColdAtk = ItemMap[self.Name]['MaxColdAtk'],
                         MinToxinAtk = ItemMap[self.Name]['MinToxinAtk'],
                         MaxToxinAtk = ItemMap[self.Name]['MaxToxinAtk'],
                         Turned = ItemMap[self.Name]['Turned'][random.randint(0,(len(ItemMap[self.Name]['Turned'])-1))],
                         ToxinType = ItemMap[self.Name]['ToxinType'][random.randint(0,(len(ItemMap[self.Name]['ToxinType'])-1))],
                         Tainted = ItemMap[self.Name]['Tainted'][random.randint(0,(len(ItemMap[self.Name]['Tainted'])-1))],
                         Magical = ItemMap[self.Name]['Magical'][random.randint(0,(len(ItemMap[self.Name]['Magical'])-1))],
                         MagicAttributes = ItemMap[self.Name]['MagicAttributes'],
                         Fixed = ItemMap[self.Name]['Fixed'])
        self.Weight = random.randint(self.MinWeight,self.MaxWeight)
        self.Durability = random.randint(self.MinDurability,self.MaxDurability)
        self.Atk = random.randint(self.MinAtk,self.MaxAtk)
        self.FireAtk = random.randint(self.MinFireAtk, self.MaxFireAtk)
        self.ElectricAtk = random.randint(self.MinElectricAtk, self.MaxElectricAtk)
        self.ColdAtk = random.randint(self.MinColdAtk, self.MaxColdAtk)
        self.ToxinAtk = random.randint(self.MinToxinAtk, self.MaxToxinAtk)
        self.SocketCount = random.randint(self.MinSocketCount, self.MaxSocketCount)
        self.BonusExp = random.randint(self.MinBonusExp, self.MaxBonusExp)
        self.Defence = random.randint(self.MinDefence, self.MaxDefence)

